name: '[Dev]  zypress - GitHub Actions'

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main

env:
  env: 'prd'
  project: 'zypress'
  aws_region: 'us-east-2'

jobs:
  ecr:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: AWS IAM Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          role-session-name: GH-Actions-${{ env.project }}

      - name: Who Am I?
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          #ECR_REPOSITORY: ${{ env.project }}-${{ env.env }}
          ECR_REPOSITORY: ${{ env.project }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.project }}-image .
          docker tag ${{ env.project }}-image $ECR_REGISTRY/$ECR_REPOSITORY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}